apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-kafka
  labels:
    app: demo-spring-boot-kafka
spec:
  type: NodePort
  selector:
    app: demo-spring-boot-kafka
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot-kafka
spec:
  selector:
    matchLabels:
      app: demo-spring-boot-kafka
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-spring-boot-kafka
    spec:
      containers:
        - name: demo-spring-boot-kafka
          image: demo-spring-boot-kafka:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_ENDPOINT
              value: kafka:9092
